title: Folly Beach Baptist Church
# subtitle: "At The Edge of America"
title_separator: "|"
logo: "/assets/images/88x88.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
minimal_mistakes_skin:
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
whitelist:
  - jekyll-redirect-from
 
# Outputting
permalink: /
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
location: Folly Beach, SC

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name   : "Service Times"
 # avatar : "/assets/images/bio-photo.jpg"
  bio    : "Sunday School 9:45am Sunday Mornings 11:00am Sunday Evenings - Check Our Schedule and Events Pages
  form action="https://secure.myvanco.com/L-Z0TS" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="XW28R4GEGTAW6">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>"
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
