# Navigation bar
logo: "/assets/images/88x88.png"
title: Folly Beach Baptist Church
  # subtitle: "At The Edge of America"
search: false

# Site settings
title_separator: "|"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
minimal_mistakes_skin: "dirt"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
whitelist:
  - jekyll-redirect-from
 
# Outputting
permalink: /
include:
  - _pages

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

# Left sidebar
author:
  location: "Folly Beach, SC"
  name   : "Service Times"
 # avatar : "/assets/images/bio-photo.jpg"
  bio: "Sunday School 9:45am <br> Sunday Mornings 11:00am <br> Sunday Evenings - Check Our Schedule and Events Pages"
  links:
    - label: "Give Online"
      icon: "fas fa-fw fa-link"
      url: "https://secure.myvanco.com/L-Z0TS/home"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      url: "https://www.facebook.com/FollyBeachBaptistChurch/"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      url: "https://www.facebook.com/FollyBeachBaptistChurch/"
     - label: "Give Online"
      icon: "fas fa-fw fa-link"
      url: "https://secure.myvanco.com/L-Z0TS/home"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
