title: Folly Beach Baptist Church
subtitle: "At The Edge of America"
logo: "/assets/images/88x88.png"
description:
  A small friendly and loving church situated in a beachfront community in Folly Beach, South
  Carolina.

# Left Sidebar
author:
  bio:
    "<h3>Service Times</h3><b>Sunday School</b><br> 9:45am <br><b>Sunday Morning</b><br> 11:00am <br><b>Sunday
    Evenings</b><br>See Calendar"
  links:
    - label: "Give Online"
      icon: "fas fa-hand-holding-usd fa-fw"
      url: "https://secure.myvanco.com/L-Z0TS/home"
    - label: "Email Us"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your.info@follybeachbaptist.com "
    - label: "Facebook"
      icon: "fab fa-facebook fa-fw"
      url: "https://www.facebook.com/FollyBeachBaptistChurch/"

# Build settings
title_separator: "|"
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin:
search: false
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
permalink: /
include:
  - _pages
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
