title: Folly Beach Baptist Church
subtitle: "At The Edge of America"
title_separator: "|"
logo: "/assets/images/88x88.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
minimal_mistakes_skin: "air"
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
whitelist:
  - jekyll-redirect-from
 
# Outputting
permalink: /
include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name   : "Service Times"
  bio: "Sunday School 9:45am <br> Sunday Mornings 11:00am <br> Sunday Evenings - Check Our Schedule and Events Pages"
  links:
    - label: "Give Online"
      icon: "fas fa-hand-holding-usd fa-fw"
      url: "https://secure.myvanco.com/L-Z0TS/home"
    - label: "Facebook"
      icon: "fa-brands fa-facebook fa-fw"
      url: "https://www.facebook.com/FollyBeachBaptistChurch/"

footer:
  links:
    - label: "Give Online"
      icon: "fas fa-hand-holding-usd fa-fw"
      url: "https://secure.myvanco.com/L-Z0TS/home"
    - label: "Facebook"
      icon: "fa-brands fa-facebook fa-fw"
      url: "https://www.facebook.com/FollyBeachBaptistChurch/"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
