title: Folly Beach Baptist Church
subtitle: "At The Edge of America"
title_separator: "|"
logo: "/assets/images/88x88.png"
email:
description:
  A small friendly and loving church situated in a beachfront community in Folly Beach, South
  Carolina.

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin:
search: false
whitelist:
  - jekyll-redirect-from

# Outputting
permalink: /
include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name: "Service Times"
  bio:
    "<b>Sunday School</b><br> 9:45am <br><b>Sunday Morning</b><br> 11:00am <br><b>Sunday
    Evenings</b><br>See Calendar"
  links:
    - label: "Give Online"
      icon: "fas fa-hand-holding-usd fa-fw"
      url: "https://secure.myvanco.com/L-Z0TS/home"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your.info@follybeachbaptist.com "
    - label: "Facebook"
      icon: "fab fa-facebook fa-fw"
      url: "https://www.facebook.com/FollyBeachBaptistChurch/"

footer:
  links:
    - label: "Give Online"
      icon: "fas fa-hand-holding-usd fa-fw"
      url: "https://secure.myvanco.com/L-Z0TS/home"
    - label: "Facebook"
      icon: "fab fa-facebook fa-fw"
      url: "https://www.facebook.com/FollyBeachBaptistChurch/"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
